.\" 
.TH "HEXTRIM" "1" "Oct 2008" "Vincenzo La Spesa" "User Commands"
.SH "NAME"
hextrim \- delete characters binary string
.SH "SYNOPSIS"
.B hextrim
\fIHexString \fR
.SH "DESCRIPTION"
Delete binary strings from standard input, writing to standard output.

EXAMPLES

cat foo.dat |hextrim CACA >> bar.dat
.SH "AUTHOR"
Written by Vincenzo La Spesa.

http://thedarshan.com/
.SH "REPORTING BUGS"
Report bugs to <https://github.com/VincenzoLaSpesa/hextrim>.
.SH "COPYRIGHT"
Copyright \(co 2008 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
.br 
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
